#ifndef GAME_GAME_EVENT_QUEUE_H
#define GAME_GAME_EVENT_QUEUE_H

#include "Game/Event.h"
#include "Game/EventDataTypes.h"

struct UnidentifiedEventData_80065E10;
struct GoalScoredData;
struct UnidentifiedEventData_80066008;
struct UnidentifiedEventData_800661C0;
struct ReceiveBallData;
struct UnidentifiedEventData_800663A8;
struct UnidentifiedEventData_8006649C;
struct ShotAtGoalData;
struct PlayerAttackData;
struct UnidentifiedEventData_80066A04;
struct UnidentifiedEventData_80066B08;
struct CollisionChainPlayerData;
struct UnidentifiedEventData_80066E14;
struct UnidentifiedEventData_80066F18;
struct UnidentifiedEventData_8006701C;
struct LightningStrikeData;
struct UnidentifiedEventData_80067214;
struct MegaStrikeEndData;
struct UnidentifiedEventData_800673FC;
struct UnidentifiedEventData_800676D8;
struct UnidentifiedEventData_800678D0;

class UnidentifiedGameEventQueue
{
public:
    UnidentifiedGameEventQueue();

    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent00;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent01;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent02;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent03;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent04;
    UnidentifiedQueuedEvent<UnidentifiedEventData_80065E10> mEvent05;
    UnidentifiedEvent<GoalScoredData> mEvent06;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent07;
    UnidentifiedQueuedEvent<UnidentifiedEventData_80066008> mEvent08;
    UnidentifiedEvent<UnidentifiedEventNoData> mEvent09;
    UnidentifiedEvent<UnidentifiedEventNoData> mEvent10;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent11;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent12;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent13;
    UnidentifiedEvent<UnidentifiedEventData_800661C0> mEvent14;
    UnidentifiedEvent<ReceiveBallData> mEvent15;
    UnidentifiedEvent<UnidentifiedEventData_800663A8> mEvent16;
    UnidentifiedEvent<UnidentifiedEventData_8006649C> mEvent17;
    UnidentifiedEvent<UnidentifiedEventData_8006649C> mEvent18;
    UnidentifiedEvent<UnidentifiedEventData_8006649C> mEvent19;
    UnidentifiedEvent<UnidentifiedEventData_8006649C> mEvent20;
    UnidentifiedEvent<UnidentifiedEventData_8006649C> mEvent21;
    UnidentifiedQueuedEvent<ShotAtGoalData> mEvent22;
    UnidentifiedEvent<ShotAtGoalData> mEvent23;
    UnidentifiedEvent<PlayerAttackData> mEvent24;
    UnidentifiedEvent<PlayerAttackData> mEvent25;
    UnidentifiedEvent<PlayerAttackData> mEvent26;
    UnidentifiedEvent<PlayerAttackData> mEvent27;
    UnidentifiedQueuedEvent<PlayerAttackData> mEvent28;
    UnidentifiedQueuedEvent<PlayerAttackData> mEvent29;
    UnidentifiedQueuedEvent<CollisionPlayerWallData> mEvent30;
    UnidentifiedQueuedEvent<UnidentifiedEventData_80066A04> mEvent31;
    UnidentifiedQueuedEvent<UnidentifiedEventData_80066B08> mEvent32;
    UnidentifiedQueuedEvent<CollisionChainPlayerData> mEvent33;
    UnidentifiedQueuedEvent<CollisionWindDebrisPlayerData> mEvent34;
    UnidentifiedQueuedEvent<UnidentifiedEventData_80066E14> mEvent35;
    UnidentifiedQueuedEvent<ShotAtGoalData> mEvent36;
    UnidentifiedQueuedEvent<ShotAtGoalData> mEvent37;
    UnidentifiedQueuedEvent<UnidentifiedEventData_80066F18> mEvent38;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent39;
    UnidentifiedEvent<UnidentifiedEventData_8006701C> mEvent40;
    UnidentifiedEvent<UnidentifiedEventData_8006701C> mEvent41;
    UnidentifiedEvent<UnidentifiedEventData_8006701C> mEvent42;
    UnidentifiedEvent<UnidentifiedEventNoData> mEvent43;
    UnidentifiedQueuedEvent<LightningStrikeData> mEvent44;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent45;
    UnidentifiedEvent<UnidentifiedEventData_80067214> mEvent46;
    UnidentifiedEvent<MegaStrikeEndData> mEvent47;
    UnidentifiedEvent<UnidentifiedEventNoData> mEvent48;
    UnidentifiedEvent<UnidentifiedEventNoData> mEvent49;
    UnidentifiedEvent<UnidentifiedEventNoData> mEvent50;
    UnidentifiedEvent<UnidentifiedEventNoData> mEvent51;
    UnidentifiedEvent<UnidentifiedEventNoData> mEvent52;
    UnidentifiedEvent<UnidentifiedEventNoData> mEvent53;
    UnidentifiedEvent<UnidentifiedEventData_800673FC> mEvent54;
    UnidentifiedEvent<UnidentifiedEventData_800673FC> mEvent55;
    UnidentifiedEvent<UnidentifiedEventData_800673FC> mEvent56;
    UnidentifiedEvent<UnidentifiedEventData_800673FC> mEvent57;
    UnidentifiedEvent<UnidentifiedEventData_80067214> mEvent58;
    UnidentifiedEvent<UnidentifiedEventData_80067214> mEvent59;
    UnidentifiedEvent<UnidentifiedEventData_80067214> mEvent60;
    UnidentifiedEvent<UnidentifiedEventData_80067214> mEvent61;
    UnidentifiedEvent<UnidentifiedEventData_80067214> mEvent62;
    UnidentifiedEvent<CollisionBulletBillData> mEvent63;
    UnidentifiedEvent<cFielder> mEvent64;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent65;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent66;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent67;
    UnidentifiedQueuedEvent<UnidentifiedEventData_800676D8> mEvent68;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent69;
    UnidentifiedQueuedEvent<UnidentifiedEventNoData> mEvent70;
    UnidentifiedEvent<CharacterImpactEvent> mEvent71;
    UnidentifiedEvent<CharacterImpactEvent> mEvent72;
    UnidentifiedEvent<CharacterImpactEvent> mEvent73;
    UnidentifiedQueuedEvent<UnidentifiedEventData_800678D0> mEvent74;
};

#endif // GAME_GAME_EVENT_QUEUE_H
